<?php

namespace AppBundle\Repository;

/**
 * discographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class discographyRepository extends \Doctrine\ORM\EntityRepository
{
}
