<?php

namespace AppBundle\Repository;

/**
 * discography_has_rsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class discography_has_rsRepository extends \Doctrine\ORM\EntityRepository
{
}
