<?php

namespace AppBundle\Repository;

/**
 * disco_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class disco_typeRepository extends \Doctrine\ORM\EntityRepository
{
}
