imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.rs_images: /img/rs
    app.path.discography_images: /img/covers

framework:
    #esi: ~
    translator: { fallbacks: ['en'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# EasyAdminBundle Configuration
easy_admin:
    site_name: 'Waffle Music - Admin'
    design:
      brand_color: '#6C4885'
      menu: [{ entity: 'discography', label: 'Discographies' }, { entity: 'discography_has_rs', label: 'Liens (URLs)' }, { entity: 'disco_type', label: 'Types de discographies' }, { entity: 'rs', label: 'Réseaux-sociaux' }]
      assets:
            favicon: '/img/favicons_v2/favicon.ico'
    entities:
        discography:
          class: AppBundle\Entity\discography
          new:
            fields:
              - { property: 'discoTypeId', type_options: { required: true } }
          list:
              title: 'Waffle Admin - Discographie'
              actions:
                - { name: 'new', label: 'Ajouter discographie' }
              fields:
                  - { property: 'title' , label: 'Titre' }
                  - { property: 'author' , label: 'Auteur' }
                  - { property: 'image', type: 'image', base_path: '%app.path.discography_images%' }
                  - { property: 'discoTypeId' , label: 'Type de discographie' }
          form:
              fields:
                  - { property: 'title' , label: 'Titre' }
                  - { property: 'author' , label: 'Auteur' }
                  - { property: 'imageFile', type: 'vich_image' , label: 'Image' }
                  - { property: 'discoTypeId' , label: 'Type de discographie' }
        discography_has_rs:
          class: AppBundle\Entity\discography_has_rs
          new:
            fields:
              - { property: 'discographyId', type_options: { required: true } }
              - { property: 'rsId', type_options: { required: true } }
          list:
            title: 'Waffle Admin - Liens (URLs)'
            actions:
              - { name: 'new', label: 'Ajouter un lien' }
            fields:
              - { property: 'discographyId', label: 'Discographie' }
              - { property: 'link', label: 'Lien (url)' }
              - { property: 'rsId', label: 'Réseau' }
          form:
            fields:
              - { property: 'discographyId', label: 'Discographie' }
              - { property: 'link', label: 'Lien (url)' }
              - { property: 'rsId', label: 'Réseau' }
        rs:
          class: AppBundle\Entity\rs
          disabled_actions: ['delete']
          list:
              title: 'Waffle Admin - Réseaux-sociaux'
              actions:
                - { name: 'new', label: 'Ajouter réseau' }
              fields:
                - { property: 'name' }
                - { property: 'image', type: 'image', base_path: '%app.path.rs_images%' }
          show:
              fields:
                - { property: 'name' }
                - { property: 'image', type: 'image', base_path: '%app.path.rs_images%' }
          form:
              fields:
                - { property: 'name'}
                - { property: 'imageFile', type: 'vich_image' }
        disco_type:
            class: AppBundle\Entity\disco_type
            disabled_actions: ['delete']
            list:
              title: 'Waffle Admin - Type de discographie'
              actions:
                - { name: 'new', label: 'Ajouter type de disco' }
              fields:
                - { property: 'name' }
            show:
              fields:
                - { property: 'name' }


# VichUploaderBundle Configuration
vich_uploader:
    db_driver: orm
    mappings:
      rs_images:
        uri_prefix: '%app.path.rs_images%'
        upload_destination: '%kernel.root_dir%/../web/img/rs'
      discography_images:
        uri_prefix: '%app.path.discography_images%'
        upload_destination: '%kernel.root_dir%/../web/img/covers'
