# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    baptiste.drillien:
                        password: $2y$12$uWr.OZyIfo4B.pU1hI4PCOLMx4gL7ulInPUf9jed1v0UKV.fFhfpe
                        roles: 'ROLE_ADMIN'
                    theo.leroy:
                        password: $2y$12$W.FcdT5db1A4SRfGig4piOpEfgQqEFlagcqOgFpHXgwX547yMJTUG
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/store_mail, roles: ROLE_ADMIN }
        - { path: ^/demo_mail, roles: ROLE_ADMIN }
